version: "2.0"

services:

  postgresql-db:
    image: postgres:10.5-alpine
    environment:
      POSTGRES_DB: stock_manager_db
      POSTGRES_USER: alaz
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
      - "5433:5433"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '8888:80'
    depends_on:
      - postgresql-db
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@alaz.info'
      PGADMIN_DEFAULT_PASSWORD: 'admin'